export type SeedCircuit = {
  slug: string;
  name: string;
  country: string;
  location: string;
  lengthKm: number;
  turns: number;
  lapsStandard: number;
  firstGpYear?: number;
  dataConfidence: "verified" | "placeholder" | "uncertain";
};

/**
 * The venues of the 2026 season, so every race in the calendar has a circuit behind it.
 *
 * Length and turn counts are the current configuration, taken from each circuit's article
 * (see DATA_SOURCES.md). `firstGpYear` is the first World Championship Grand Prix at the
 * venue, which is why Silverstone reads 1950 rather than the 1948 pre-championship race,
 * and Mexico City 1963 rather than the non-championship 1962 event.
 *
 * `lapsStandard` is derived, not guessed: the sporting regulations set a race at the fewest
 * complete laps exceeding 305 km, with Monaco the standing exception at 260 km. Applying
 * that to the verified lengths reproduces the figure the brief itself gives for Monza, 53.
 *
 * Lap records are still absent — they need a separate verification pass.
 */
export const seedCircuits: SeedCircuit[] = [
  {
    slug: "albert-park",
    name: "Albert Park Circuit",
    country: "Australia",
    location: "Melbourne",
    lengthKm: 5.278,
    turns: 16,
    lapsStandard: 58,
    firstGpYear: 1996,
    dataConfidence: "verified",
  },
  {
    slug: "shanghai",
    name: "Shanghai International Circuit",
    country: "China",
    location: "Shanghai",
    lengthKm: 5.451,
    turns: 16,
    lapsStandard: 56,
    firstGpYear: 2004,
    dataConfidence: "verified",
  },
  {
    slug: "suzuka",
    name: "Suzuka International Racing Course",
    country: "Japan",
    location: "Suzuka",
    lengthKm: 5.807,
    turns: 18,
    lapsStandard: 53,
    firstGpYear: 1987,
    dataConfidence: "verified",
  },
  {
    slug: "miami",
    name: "Miami International Autodrome",
    country: "United States",
    location: "Miami Gardens, Florida",
    lengthKm: 5.412,
    turns: 19,
    lapsStandard: 57,
    firstGpYear: 2022,
    dataConfidence: "verified",
  },
  {
    slug: "gilles-villeneuve",
    name: "Circuit Gilles Villeneuve",
    country: "Canada",
    location: "Montreal",
    lengthKm: 4.361,
    turns: 14,
    lapsStandard: 70,
    firstGpYear: 1978,
    dataConfidence: "verified",
  },
  {
    slug: "monaco",
    name: "Circuit de Monaco",
    country: "Monaco",
    location: "Monte Carlo",
    lengthKm: 3.337,
    turns: 19,
    // The regulations' standing exception: Monaco runs to 260 km rather than 305.
    lapsStandard: 78,
    firstGpYear: 1950,
    dataConfidence: "verified",
  },
  {
    slug: "barcelona-catalunya",
    name: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    location: "Montmeló",
    lengthKm: 4.657,
    turns: 14,
    lapsStandard: 66,
    firstGpYear: 1991,
    dataConfidence: "verified",
  },
  {
    slug: "red-bull-ring",
    name: "Red Bull Ring",
    country: "Austria",
    location: "Spielberg",
    lengthKm: 4.326,
    turns: 10,
    lapsStandard: 71,
    firstGpYear: 1970,
    dataConfidence: "verified",
  },
  {
    slug: "silverstone",
    name: "Silverstone Circuit",
    country: "United Kingdom",
    location: "Silverstone",
    lengthKm: 5.891,
    turns: 18,
    lapsStandard: 52,
    firstGpYear: 1950,
    dataConfidence: "verified",
  },
  {
    slug: "spa-francorchamps",
    name: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    location: "Stavelot",
    lengthKm: 7.004,
    turns: 20,
    lapsStandard: 44,
    firstGpYear: 1950,
    dataConfidence: "verified",
  },
  {
    slug: "hungaroring",
    name: "Hungaroring",
    country: "Hungary",
    location: "Mogyoród",
    lengthKm: 4.381,
    turns: 14,
    lapsStandard: 70,
    firstGpYear: 1986,
    dataConfidence: "verified",
  },
  {
    slug: "zandvoort",
    name: "Circuit Zandvoort",
    country: "Netherlands",
    location: "Zandvoort",
    lengthKm: 4.259,
    turns: 14,
    lapsStandard: 72,
    firstGpYear: 1952,
    dataConfidence: "verified",
  },
  {
    slug: "monza",
    name: "Autodromo Nazionale Monza",
    country: "Italy",
    location: "Monza",
    lengthKm: 5.793,
    turns: 11,
    lapsStandard: 53,
    firstGpYear: 1950,
    dataConfidence: "verified",
  },
  {
    slug: "madring",
    name: "Madring",
    country: "Spain",
    location: "Madrid",
    lengthKm: 5.416,
    turns: 22,
    lapsStandard: 57,
    // Built for 2026; it has hosted no Grand Prix at the time of this seed.
    dataConfidence: "uncertain",
  },
  {
    slug: "baku",
    name: "Baku City Circuit",
    country: "Azerbaijan",
    location: "Baku",
    lengthKm: 6.003,
    turns: 20,
    lapsStandard: 51,
    firstGpYear: 2016,
    dataConfidence: "verified",
  },
  {
    slug: "bahrain",
    name: "Bahrain International Circuit",
    country: "Bahrain",
    location: "Sakhir",
    lengthKm: 5.412,
    turns: 15,
    lapsStandard: 57,
    firstGpYear: 2004,
    dataConfidence: "verified",
  },
  {
    slug: "marina-bay",
    name: "Marina Bay Street Circuit",
    country: "Singapore",
    location: "Marina Bay",
    lengthKm: 4.927,
    turns: 19,
    lapsStandard: 62,
    firstGpYear: 2008,
    dataConfidence: "verified",
  },
  {
    slug: "circuit-of-the-americas",
    name: "Circuit of the Americas",
    country: "United States",
    location: "Austin, Texas",
    lengthKm: 5.513,
    turns: 20,
    lapsStandard: 56,
    firstGpYear: 2012,
    dataConfidence: "verified",
  },
  {
    slug: "hermanos-rodriguez",
    name: "Autódromo Hermanos Rodríguez",
    country: "Mexico",
    location: "Mexico City",
    lengthKm: 4.304,
    turns: 17,
    lapsStandard: 71,
    firstGpYear: 1963,
    dataConfidence: "verified",
  },
  {
    slug: "interlagos",
    name: "Autódromo José Carlos Pace",
    country: "Brazil",
    location: "São Paulo",
    lengthKm: 4.309,
    turns: 15,
    lapsStandard: 71,
    firstGpYear: 1973,
    dataConfidence: "verified",
  },
  {
    slug: "las-vegas",
    name: "Las Vegas Strip Circuit",
    country: "United States",
    location: "Paradise, Nevada",
    lengthKm: 6.201,
    turns: 17,
    lapsStandard: 50,
    firstGpYear: 2023,
    dataConfidence: "verified",
  },
  {
    slug: "lusail",
    name: "Lusail International Circuit",
    country: "Qatar",
    location: "Lusail",
    lengthKm: 5.419,
    turns: 16,
    lapsStandard: 57,
    firstGpYear: 2021,
    dataConfidence: "verified",
  },
  {
    slug: "yas-marina",
    name: "Yas Marina Circuit",
    country: "United Arab Emirates",
    location: "Abu Dhabi",
    lengthKm: 5.281,
    turns: 16,
    lapsStandard: 58,
    firstGpYear: 2009,
    dataConfidence: "verified",
  },
];
